### ISSUE TITLE
Silithus Dungeon Queue

### ISSUE THREAD

**Issue by caleb-sexton** [Nostralia/Bugtracker#73]
Calandrath is offering to let players join dungeon finder queues. I think that's unintended!

![image](https://user-images.githubusercontent.com/5790441/33522922-3a8198d8-d84d-11e7-8790-b5a70a9b5048.png)
![image](https://user-images.githubusercontent.com/5790441/33522923-40fb31b0-d84d-11e7-8251-733ab6868109.png)
![image](https://user-images.githubusercontent.com/5790441/33522925-46b3ef3e-d84d-11e7-92a1-08180eae8b1c.png)
![image](https://user-images.githubusercontent.com/5790441/33522926-4b441a2e-d84d-11e7-9100-daeab075d200.png)

**Comment by ghost** [comment]
World of Warcraft Client Patch 1.5.0 (2005-06-07)
- Innkeepers around the world now have a gossip option that lets you 
  join a meeting stone directly from the innkeeper rather than going to 
  the location of the meeting stone. Also these Innkeepers will now 
  have background lore about each of the dungeons.

**Comment by caleb-sexton** [comment]
@NolinNostralia Haha that's amazing! FWIW it actually works perfectly by the way.
